server:
  shutdown: graceful

spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true



