server:
  shutdown: graceful
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12


spring:
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.101.11:5432/mydb
#    username: junny
#    password: 1234
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa


